export const CART_ACTION_TYPES = {
    SET_CART_ITEMS : 'cart/SET_CART_ITEMS',
    TOGGLE_CART_SHOWN: 'cart/TOGGLE_CART_SHOWN',
    ADD_CART_ITEM: 'cart/ADD_CART_ITEM',
    REMOVE_CART_ITEM: 'cart/REMOVE_CART_ITEM',
    DECREASE_CART_ITEM: 'cart/DECREASE_CART_ITEM',
}