name: semantic-releases-on-commit
run-name: ${{ github.actor }} made a commit, building new version for ${{ github.repository }}
on:
  push:
    branches:
      - main
jobs:
  tag-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Semantic Release 
        uses: cycjimmy/semantic-release-action@v4
        with:
          branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

